// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaNJBjhSU7Cxa6hiL21de9n3zt7mB5jg',
    appId: '1:934484241138:web:fb3e5a5dedd8873b9afe6b',
    messagingSenderId: '934484241138',
    projectId: 'mental-wellness-app-64cb6',
    authDomain: 'mental-wellness-app-64cb6.firebaseapp.com',
    storageBucket: 'mental-wellness-app-64cb6.firebasestorage.app',
    measurementId: 'G-TSZKD55857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCzmwiseZ19KpYqc3njrCCTDPJFavySY',
    appId: '1:934484241138:android:4f6596e1c6c0dd049afe6b',
    messagingSenderId: '934484241138',
    projectId: 'mental-wellness-app-64cb6',
    storageBucket: 'mental-wellness-app-64cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdGVf4rHvnHyT2pR2H_-heR3iuvpPznE',
    appId: '1:934484241138:ios:ab4df9bb0d9fe9e59afe6b',
    messagingSenderId: '934484241138',
    projectId: 'mental-wellness-app-64cb6',
    storageBucket: 'mental-wellness-app-64cb6.firebasestorage.app',
    androidClientId:
        '934484241138-jvd3ve6p6h0or2kqbsgfs2ure837k675.apps.googleusercontent.com',
    iosClientId:
        '934484241138-h67280v7je94dmqsjfjgeu522c1l8flv.apps.googleusercontent.com',
    iosBundleId: 'com.mentalwellness.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCdGVf4rHvnHyT2pR2H_-heR3iuvpPznE',
    appId: '1:934484241138:ios:ab4df9bb0d9fe9e59afe6b',
    messagingSenderId: '934484241138',
    projectId: 'mental-wellness-app-64cb6',
    storageBucket: 'mental-wellness-app-64cb6.firebasestorage.app',
    androidClientId:
        '934484241138-jvd3ve6p6h0or2kqbsgfs2ure837k675.apps.googleusercontent.com',
    iosClientId:
        '934484241138-h67280v7je94dmqsjfjgeu522c1l8flv.apps.googleusercontent.com',
    iosBundleId: 'com.mentalwellness.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKaNJBjhSU7Cxa6hiL21de9n3zt7mB5jg',
    appId: '1:934484241138:web:76765e84e23f7bf69afe6b',
    messagingSenderId: '934484241138',
    projectId: 'mental-wellness-app-64cb6',
    authDomain: 'mental-wellness-app-64cb6.firebaseapp.com',
    storageBucket: 'mental-wellness-app-64cb6.firebasestorage.app',
    measurementId: 'G-7RV1RVGBE8',
  );
}
